# Konfigurasi Koneksi ke Laragon MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/libborrow_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Konfigurasi JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect