# Konfigurasi Koneksi ke Laragon MySQL
spring.datasource.url=jdbc:mysql://bcl9gqxokkxpl5y16j4s-mysql.services.clever-cloud.com:3306/bcl9gqxokkxpl5y16j4s
spring.datasource.username=utresb5hnce9k9fj
spring.datasource.password=mhVaHofWFjKxabjdk5Kr

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Konfigurasi JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect